#ifndef SECRETS_H
#define SECRETS_H

#define MQTT_THINGSPEAK_CHANNEL_ID "3239989"
#define MQTT_THINGSPEAK_API_KEY "XQDV2QP4E3CW5R0J"
#define MQTT_THINGSPEAK_CLIENT_ID "HSAKNAsaFDQNEw0SMgowOAk"

#endif
